language: objective-c
osx_image: xcode8.3.2
xcode_project: socialNetwork.xcodeproj
xcode_scheme: socialNetwork
cache:
  directories:
  - Cathage
before_install:
- curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.24.0/Carthage.pkg"
- sudo installer -pkg "Carthage.pkg" -target /
- curl -L -O https://github.com/YPlan/CartfileDiff/releases/download/0.1/CartfileDiff.pkg
- sudo installer -pkg CartfileDiff.pkg -target /
- rm "Carthage.pkg"
- gem install xcpretty
before_script:
- carthage bootstrap --platform iOS
script:
- set -o pipefail
- scripts/bootstrap-if-needed.sh
- xcodebuild build -workspace socialNetwork.xcworkspace -sdk iphonesimulator -scheme socialNetwork -configuration Debug -destination "platform=iOS Simulator,name=iPhone 6" -destination "platform=iOS Simulator,name=iPhone 7 Plus" | xcpretty -c
notifications:
  email:
    recipients:
      - sabrine.elbahri@3ie.fr
    on_success: change
    on_failure: always
